### ISSUE TITLE
Config not working

### ISSUE THREAD

**Issue by APolarBaer** [Vanhal/Recall-Stones#18]
trying to change the configs for my 1.9.4 server and it seems that they dont change much

# Configuration file

dimensionstone {
    I:chargesPerUse=1
    I:maxCharge=10

general {
    I:chargesPerPearl=3

recallstone {
    I:chargesPerUse=1
    I:maxCharge=20

![image](https://cloud.githubusercontent.com/assets/19779692/16563718/a43ba4f8-41d1-11e6-93a8-dd0d8d86391c.png)

![image](https://cloud.githubusercontent.com/assets/19779692/16563703/83ab4b4e-41d1-11e6-8c25-f5bc17d95ba8.png)

**Comment by Vanhal** [comment]
You'll need to change configs on both the server and the client. They don't sync.

**Comment by APolarBaer** [comment]
well aren't i just an idiot. thanks for the fast reply lol

**Comment by Vanhal** [comment]
np, some day I'll figure out how to do config syncing...

**Comment by APolarBaer** [comment]
no worries, maybe include it somewhere that they currently dont sync? unless you have and i just missed it lmfao
